version: '3.8'

services:
  edge-tts:
    build: .
    container_name: arsa-edge-tts
    ports:
      - "0.0.0.0:8021:8021"
    volumes:
      - tts_output:/app/output
    environment:
      - PYTHONUNBUFFERED=1
      - TTS_MAX_TEXT_LENGTH=5000
      - TTS_CLEANUP_INTERVAL=3600
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8021/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - tts-network

networks:
  tts-network:
    driver: bridge

volumes:
  tts_output:
    driver: local